CREATE TABLE IF NOT EXISTS `Teacher` (
  `teacher_id` int(8) unsigned NOT NULL AUTO_INCREMENT,
  `teacher_photo_path` varchar(60) NOT NULL,
  `teacher_name` varchar(20) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `teacher_sn` varchar(50) NOT NULL, CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `teacher_sn2` varchar(50) NOT NULL, CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `teacher_official_id` varchar(9) NOT NULL,
  `teacher_birthdate` date NOT NULL,
  `teacher_birthplace` varchar(50) CHARACTER SET latin1 COLLATE latin1_spanish_ci DEFAULT NULL,
  `teacher_address` varchar(50) NOT NULL,
  `teacher_address2` varchar(50) DEFAULT NULL,
  `teacher_homePostalAddress` int(5) NOT NULL,
  `teacher_phone` int(9) NOT NULL,
  `teacher_dpt_id` int(8) NOT NULL,
  `teacher_situation_id` int(8) NOT NULL,
  `teacher_title` varchar(200) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `teacher_catLevel` varchar(20) CHARACTER SET latin1 COLLATE latin1_spanish_ci DEFAULT NULL,
  `teacher_specialty` varchar(50) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `teacher_town_id` int(8) unsigned NOT NULL,
  `teacher_observations` varchar(300) CHARACTER SET latin1 COLLATE latin1_spanish_ci DEFAULT NULL,
  `teacher_entryDate` datetime NOT NULL,
  `teacher_last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `teacher_creationUserID` int(11) unsigned NOT NULL,
  `teacher_lastupdateUserId` int(11) NOT NULL,
  `teacher_markedForDeletion` enum('n','y') NOT NULL,
  `teacher_markedForDeletionDate` datetime NOT NULL,
  PRIMARY KEY (`teacher_id`),
  KEY `teacher_town_id` (`teacher_town_id`),
  KEY `teacher_town_id_2` (`teacher_town_id`),
  KEY `teacher_creationUserID` (`teacher_creationUserID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;